[build]
builder = "nixpacks"
buildCommand = "pip install poetry==1.3.1 && poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi"

[deploy]
startCommand = "poetry run uvicorn src.app:app --host 0.0.0.0 --port $PORT --log-level info"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
healthcheckInterval = 30 